name: nhom_4_quan_ly_khoa_hoc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0  # Thêm package http để gọi API
  shared_preferences: ^2.5.4 # Thêm package shared_preferences để lưu trữ dữ liệu cục bộ
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Bạn có thể thêm assets nếu cần
  # assets:
  #   - images/
